### PR TITLE
Create Aaron.txt

### PR DESCRIPTION
**Pull request by WAaron-500**
best branch should squash and merge... did my own code review... lgtm

### CODE REVIEW

**Review by hadley31 — CHANGES_REQUESTED** [review]
Denied

**Comment by WAaron-500** [comment]
> Denied


why?:(

**Comment by hadley31** [comment]
> > Denied
> 
> why?:(

Approved

**Review by hadley31 — APPROVED** [review]

**Comment by WAaron-500** [comment]
> > > Denied
> > 
> > 
> > why?:(
> 
> Approved

yay! :)

**Review by shoryamalani — CHANGES_REQUESTED** [review]
Unfortunate, but we gonna use this repo for so much more that I need main clean

**Comment by WAaron-500** [comment]
> Unfortunate, but we gonna use this repo for so much more that I need main clean

what if I do anyways?

**Pull request merged**
